# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /
  #   weight: 1

  #자기소개
  - name: About
    url: about
    weight: 100 

  - parent: About
    name: Intro
    url: /author/이가은/
    weight: 200
  - parent: About
    name: I can do
    url: i_can_do
    weight: 210
  - parent: About
    name: Contact
    url: contact
    weight: 220

#플젝
  - name: Project
    url: travel_jejudo
    weight: 300

  - parent: Project
    name: 파이썬 게임
    url: travel_jejudo
    weight: 300
  - parent: Project
    name: 자바 채팅방
    url: travel_hukuoka
    weight: 300

#관심분야
  - name: Interests
    url: post #이가은 입학 어디다가 넣지...;;
    weight: 400

  - parent: Interests
    name: Interest Fields
    url: field
    weight: 400
  - parent: Interests
    name: Publications
    url: publication
    weight: 400

#여행
  - name: Travel
    url: travel_jejudo
    weight: 500

  - parent: Travel
    name: Jejudo
    url: travel_jejudo
    weight: 500
  - parent: Travel
    name: Hukuoka
    url: travel_hukuoka
    weight: 500
  - parent: Travel
    name: Danang
    url: travel_danang
    weight: 500

#즐겨찾기
  - name: Bookmarks
    url: post #이가은 입학 어디다가 넣지...;;
    weight: 600

  - parent: Bookmarks
    name: JBNU
    url: bookmarks_jbnu
    weight: 600
  - parent: Bookmarks
    name: Coding
    url: bookmarks_coding
    weight: 600
  - parent: Bookmarks
    name: Youtube
    url: bookmarks_youtube
    weight: 600
  - parent: Bookmarks
    name: Blog
    url: bookmarks_blog
    weight: 600