# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: /
  #   weight: 1

  #자기소개
  - name: About
    url: about
    weight: 100 

  - parent: About
    name: Intro
    url: /author/이가은/
    weight: 200
  - parent: About
    name: Contact
    url: contact
    weight: 210

#플젝
  - name: Project
    url: project
    weight: 300


#관심분야
  - name: Interests Fields
    url: post #이가은 입학 어디다가 넣지...;;
    weight: 400

#여행
  - name: Travel
    url: travel_jejudo
    weight: 500

  - parent: Travel
    name: Jejudo
    url: travel_jejudo
    weight: 510
  - parent: Travel
    name: Fukuoka
    url: travel_fukuoka
    weight: 520
  - parent: Travel
    name: Danang
    url: travel_danang
    weight: 530

#즐겨찾기
  - name: Bookmarks
    url: post 
    weight: 600

  - parent: Bookmarks
    name: JBNU
    url: bookmarks_jbnu
    weight: 610
  - parent: Bookmarks
    name: Coding
    url: bookmarks_coding
    weight: 620
  - parent: Bookmarks
    name: Youtube
    url: bookmarks_youtube
    weight: 630
  - parent: Bookmarks
    name: Blog
    url: bookmarks_blog
    weight: 640